site_name: readthedocs 学习笔记
site_description: 个人MLIR学习笔记和心得
site_author: MLIR Learner
site_url: https://islulua.github.io/mlir-learn

# 主题配置
theme:
  name: readthedocs
  language: zh

# 导航结构
nav:
  - 首页: index.md
  - MLIR基础:
    - 概述: mlir-basics/overview.md
    - 方言系统: mlir-basics/dialects.md
    - 操作和类型: mlir-basics/ops-and-types.md
  - 实践案例:
    - 简单方言定义: examples/simple-dialect.md
    - 自定义操作: examples/custom-ops.md
    - 转换Pass: examples/transformation-pass.md
  - 高级主题:
    - 模式匹配: advanced/pattern-matching.md
    - 类型推导: advanced/type-inference.md
    - 优化策略: advanced/optimization.md
  - 参考资料:
    - 常用API: reference/common-apis.md
    - 最佳实践: reference/best-practices.md
    - 常见问题: reference/faq.md

# 插件配置
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true

# 构建配置
docs_dir: docs
site_dir: site

# 排除文件
exclude_docs: |
  images/README.md

# 额外配置
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/islulua/mlir-learn

# 国际化
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js 